name: Basic Flask Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # Uncomment the next steps one at a time to see where the error occurs

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
        
    # - name: Run tests
    #   run: |
    #     pytest

    # - name: List directory contents
    #   run: |
    #     pwd
    #     ls -la

